//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCMMarketplace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class item
    {
        public long ItemID { get; set; }
        [Required]
        public string Title { get; set; }
        [Display(Name = "Image File")]
        public string ImagePath { get; set; }
        public string Description { get; set; }
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Nullable<double> Price { get; set; }
        public string Condition { get; set; }
        public string Status { get; set; }
        public int UploadUserID { get; set; }
        public int CategoryID { get; set; }
        [ForeignKey("CategoryId")]
        public virtual category category { get; set; }
        [ForeignKey("UploadUserID")]
        public virtual user user { get; set; }
        [DataType(DataType.Upload)]
        [Display(Name = "Upload File")]
        [Required(ErrorMessage = "Please choose file to upload.")]
        public HttpPostedFileBase[] Imagefile
        {
            get; set;
        }
        public string ItemCond { get; set; }
        [Display(Name = "Select Category Name")]
        public string CategoryList { get; set; }
        public string CategoryName { get; set; }


    }
    public enum ItemCondition
    {
        New,
        BarelyUsed,
        Used
    }
}
