//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCMMarketplace.Models
{
    using System;
    using System.Collections.Generic;

    public partial class wishlist
    {
        public long ID { get; set; }
        public long ItemID { get; set; }
        public int UserID { get; set; }
    }
}
